title: ./blog
description: In depth project descriptions and more

url: http://blog.iampjt.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
 - title: Main Site
   url: http://iampjt.com
 - title: Blog Home
   url: /index.html

social:
   github: CastleCorp
   twitter: ParkerJThomas
   linkedin: parkerthomas1
   email: parker@iampjt.com

google_analytics: "UA-39800224-6"
