title: ./blog
description: In depth project descriptions and more

url: http://iampjt.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
paginate: 5

navigation:
  - title: Main Site
    url: http://iampjt.com
  - title: Blog Roll
    url: /index.html

footer-links:
   github: CastleCorp
   twitter: ParkerJThomas
   linkedin: parkerthomas1
   email: parker@iampjt.com
   instagram: ParkerJThomas
   rss: feed.xml

google_analytics: "UA-39800224-6"

email: parker@iampjt.com

gems:
  - jekyll-sitemap
